### ISSUE TITLE
入门使用Axure

### ISSUE THREAD

**Issue by baixiaoji** [baixiaoji/supplier#2]
## 这是什么东西？（明白该想project的定义）
axure主要是PM、交互提供一些产品的原型图（草图），以便将产品概念具体化的展示在开发眼前。

## 为什么要做这个东西？（想想做这个东西的动机）

1. 上周过催收11月份的需求，发现大多数后台人员几乎没有设计原型的能力，也有一个后台人员会画，但是交互逻辑有点问题。
2. 由此前端出人设计对应的原型图以及注释对应的交互，是可以更好的将原本配搭的职能变得主动商讨角色，同时也能更好的了解催收业务。
3. 给自己增加了一方面的软实力。

## 如何做这个东西？（拆解细节）
- [x] 学习软件界面知识点
- [x] 学习如何axure中业务逻辑的处理

## 回顾（项目过程中的执行、以及心态的变化）

ref:  #1

**Comment by baixiaoji** [comment]
2018-11-03
早晨起来学习了对应axure的对应的基础面板（站点地图、组件库、页面样式面板、逻辑和原件样式面板），
以及看了教程搭建一个对应的网站的原型（教程老师的登录页面）。
晚上回家的时候，看了教程中的实践一些if-else逻辑在axure上市如何实现的（增加用例）。

**Comment by baixiaoji** [comment]
2018-11-04 
学习了动态面板/全局变量/函数的功能，axure中业务逻辑的处理可以用到这些功能。
还是可以绘制出具体原型能力，也是入门咯~

**Comment by baixiaoji** [comment]
## 总结
学习对应的资料，花费了2:26:33的时间。
感觉之前评估的时间还是不是很准确的，这一点上自己还是要有一个良好的sense，不然时间花费的就是有点随意了。

在整体的学习过程中，几乎没有实践的地方，还是需要需要自己注意的地方，但是入门是使用axure的目标依旧是实现了。

**Comment by minhang-chen** [comment]
“为什么要做这个东西”的第一点中的“有点问题”写成了“优点问题”

**Comment by minhang-chen** [comment]
“为什么要做这个东西”的第一点中的“有点问题”写成了“优点问题”

**Comment by baixiaoji** [comment]
> “为什么要做这个东西”的第一点中的“有点问题”写成了“优点问题”

已更正
